# spring
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

# mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user

# Security
security:
  oauth2:
    resource:
      jwt:
        key-value: signing-key